export default {
   extends: ['stylelint-config-standard-scss'],
   plugins: ['stylelint-order'],
   rules: {
      'order/properties-order': [
         // Позиціонування
         'position',
         'top',
         'right',
         'bottom',
         'left',
         'z-index',
         // Відображення і блокова модель
         'display',
         'flex',
         'flex-direction',
         'flex-wrap',
         'justify-content',
         'align-items',
         'align-self',
         'gap',
         'grid',
         'grid-template-columns',
         'grid-template-rows',
         'grid-column',
         'grid-row',
         // Box model
         'width',
         'min-width',
         'max-width',
         'height',
         'min-height',
         'max-height',
         'margin',
         'margin-top',
         'margin-right',
         'margin-bottom',
         'margin-left',
         'padding',
         'padding-top',
         'padding-right',
         'padding-bottom',
         'padding-left',
         'border',
         'border-radius',
         'overflow',
         // Візуальне
         'background',
         'background-color',
         'background-image',
         'color',
         'opacity',
         'box-shadow',
         // Типографіка
         'font',
         'font-family',
         'font-size',
         'font-weight',
         'line-height',
         'letter-spacing',
         'text-align',
         'text-decoration',
         'text-transform',
         'white-space',
         // Анімація
         'transition',
         'animation',
         'transform',
         // Інше
         'cursor',
         'pointer-events',
         'user-select',
      ],
   },
}
